# Generated by Django 4.1.7 on 2023-04-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convmessage',
            options={'ordering': ('-created_at',)},
        ),
    ]
